{% set name = "napari-clusters-plotter" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d8d4fbfcbd2824e87d55764136eeaee0d3320d4b9727b3b42be58f34260ebf67

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.11
  run:
    - biaplotter >=0.3.1
    - imagecodecs
    - magicgui
    - napari >=0.7.0
    - npe2
    - numpy
    - pandas
    - python >=3.11
    - qtpy
    - scikit-image
    - scikit-learn
    - scipy
    - umap-learn

test:
  imports:
    - napari_clusters_plotter
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-clusters-plotter
  summary: A plugin to use with napari for clustering objects according to their properties
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/BiAPoL/napari-clusters-plotter

extra:
  recipe-maintainers:
    - haesleinhuepf
    - jaimergp
    - lazigu
    - zoccoler
    - jo-mueller
