{% set name = "napari-clusters-plotter" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: eef3a5e2afddf57808c8e61f5fc5f4c530af89c72721c381d4795bcc4606f678

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - cython >=0.27,<3  # hdbscan 0.8.33 has requirement cython<3,>=0.27
    - dask-core
    - hdbscan
    # - joblib  # not imported
    - magicgui
    - matplotlib-base
    - napari >=0.4.19
    - napari-plugin-engine >=0.1.4
    - napari-skimage-regionprops >=0.3.1
    - napari-tools-menu
    - numpy >=1.21,<=1.23.5
    - pandas
    - python >={{ python_min }}
    - qtpy
    - scikit-image
    - scikit-learn
    - scipy
    - superqt
    - umap-learn

test:
  imports:
    - napari_clusters_plotter
  commands:
    - pip list
    - pip check
  requires:
    - oclgrind
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-clusters-plotter
  summary: A plugin to use with napari for clustering objects according to their properties
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/BiAPoL/napari-clusters-plotter

extra:
  recipe-maintainers:
    - goanpeca
    - haesleinhuepf
    - jaimergp
    - lazigu
    - zoccoler
    - jo-mueller
